### ISSUE TITLE
rails model validations depending on related entities can break certain create and update scenarios

### ISSUE THREAD

**Issue by jnaglick** [graphiti-api/graphiti#93] opened 2019-02-15 23:21 UTC
Probably best understood via example:

In the graphiti specs, add the following validation to [the Employee class](https://github.com/graphiti-api/graphiti/blob/master/spec/fixtures/employee_directory.rb#L117):

`validates :positions, length: { minimum: 1, too_short: 'An employee must have at least one position!' }`

This validation will break the [persistence > nested create > creates the objects spec](https://github.com/graphiti-api/graphiti/blob/master/spec/integration/rails/persistence_spec.rb#L352).  *Despite the fact this spec attempts to create an employee with positions*, the error response will indicate "An employee must have at least one position!"

----

This appears to be a consequence of how graphiti creates and associates entities as it processes the payload. Looking at [`Graphiti::Util::Persistence#run`](https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/util/persistence.rb#L46), an entity is attempted to be persisted only once and only using its primary attributes. Only after attempting to persist the entity are its associations (parents and children) processed. This means that model validations depending upon parents and/or children do not work as expected. 

I've only given the most simple example here but this bug can manifest in different ways depending upon the exact scenario (i.e. the exact validations, relationships, and payload)

**Comment by jnaglick** [comment] 2019-02-15 23:22
I have a good deal of background on this and can probably give some more information and/or help fixing, just didn't want to add too much info to the description

**Comment by richmolj** [comment] 2019-03-03 19:28
Hey John, I know we spoke on this in Slack, is it still outstanding?

**Comment by leondmello** [comment] 2019-03-04 03:25
I understand you suggested a workaround for the library to take into account validations when saving the record. Can you post it here?

**Comment by richmolj** [comment] 2019-03-04 14:30
My suggestion was to use the `before_commit` [hook](https://www.graphiti.dev/graphiti/guides/concepts/resources#persistence-lifecycle-hooks), which fires after validations but before committing the transaction. Something like

```ruby
# in model
validates :positions,
  length: { ... },
  on: :before_commit,
  strict: true

# in resource
before_commit do |model|
  model.valid?(:before_commit)
end
```

That's pseudo-code, but should give you an idea.

**Comment by richmolj** [comment] 2019-03-07 16:36
OK looking deeper into this @jnaglick ...

So the way this works is

* save
* process/associate relationships
* look at `.errors` across all objects and render the validation payload
* `before_commit` hook

We do this because A) we want to decouple from ActiveRecord and B) children need a foreign key to the parent, so we need to save the parent first in order to get that key generated. I think this flow is correct and should not change.

Of course, the problem is we save, validations fire with no associated objects, and of course we see it as invalid. The `before_commit` recommended earlier will totally work, but you wont get the same validation error payload as normal.

There are two overall ways I can think to solve. The first is kind of hacky, check the request payload and see if the right number of associations are present:

```ruby
# very pseudo-code, YMMV
def save(model, meta)
  if meta[:relationships][:positions].length < 2
    model.errors.add(:position_length, 'no good')
  end
  super
end
```

Which stinks because you're not using normal validation errors.

A different way would be to add an `:on` for the validation:

```ruby
validates ..., on: :manual

# process the full graph

model.valid?(:manual)

# validations

# before_commit
```

IOW: we would need a hook *after* processing the full graph, but *before* validations. Similar to how we have `before_commit`, we could have `before_validation`:

```ruby
before_validation do |model|
  model.valid?(:manual)
end
```

In fact, we could do this all in the library as long as there was a convention for the `on:` option.

Does this make sense?

**Comment by jnaglick** [comment] 2019-03-07 16:50
I think you understand the problem exactly as I do, so that's great!

My only question is, are you suggesting I'd add something like 

`on: :after_jsonapi_processes_graph` 

to all my problem validations (ie, the validations that relate to other models)? 

Because if so, that seems like a coupling between AR and Resources...

**Comment by richmolj** [comment] 2019-03-07 18:09
I think better said as coupling between ActiveModel and Resources. Though not strictly required, we already more or less expect ActiveModel-compliant validations.

That said, I think it's less coupling and more a convenience when available. If you were to type it out each time, you'd have:

```ruby
before_validation do |model|
  model.valid?(:whatever)
end
```

Which would be totally decoupled. My only point is we can check to see if you have any `:whatever` validations and run them for you automatically, instead of having to type it out each time.

**Comment by elDub** [comment] 2019-03-07 18:14
For the "hacky" solution, the one that works for my needs, there was one adjustment necessary, specifically `super` must be called first because `ActiveRecord#save` clears the errors before persisting. Below (edited to match the context) is what I have so far with the assistance of @richmolj which takes into account possible incoming changes to the relationship.

```ruby
  # EmployeeResource
  def save(model, meta)
    super
    db_count = meta[:method] == :update ? model.positions.count : 0
    position_md = meta.dig(:relationships, :positions)
    md_count = position_md&.select{ |o| o.dig(:meta, :method) == :create }&.length || 0
    md_count -= position_md&.select{ |o| o.dig(:meta, :method) == :destroy }&.length || 0
    if (db_count + md_count) < 2
      model.errors.add(:positions, 'no good')
    end
    model
  end
```

**Comment by richmolj** [comment] 2019-03-07 18:19
Thanks @eldub! FWIW this could also be done in an `after_save` hook.

Though I think we all agree the `before_validation` hook would be the best solution, right @jnaglick ?

**Comment by jnaglick** [comment] 2019-03-07 18:36
@richmolj  Sorry, did mean ActiveModel, not ActiveRecord!

And yes, I think the solution with the hook sounds very clean, but I'm still questioning whether requiring `on: :whatever` in the Model validation is too strongly coupled with the Resource.

For instance, even if the lib user explicitly added

```
before_validation do |model|
  model.valid?(:whatever)
end
```

to their Resources (presumably in a shared parent class of all their Resources), rather than having that code included in the Graphiti gem itself, wouldn't there then be the problem of that validation being disabled when the model was created/updated outside of Graphiti? We could come up with a solution to this no doubt, but I think it highlights the coupling between Model<->Resource...

**Comment by richmolj** [comment] 2019-03-07 19:40
> wouldn't there then be the problem of that validation being disabled when the model was created/updated outside of Graphiti?

Yes, but I think of this as the opposite: we need to disable validations that touch associations, because graphiti persists independently. And I think it's correct to do so. But the problem is AM doesn't have a way to say "always run this, except when in this specific context" (at least I'm not aware). The best you could do is something like `if: :not_graphiti_save` which is also pretty awkward.

So I view it less as a coupling issue, and more something between a deficiency of AM:V and just the cost of doing business.

I could imagine a world where validations are completely independent of the model, and you add them to the Resource instead, but then you'd just be double-typing everything and would get out of sync.

**Comment by jnaglick** [comment] 2019-03-07 20:23
> So I view it less as a coupling issue, and more something between a deficiency of AM:V and just the cost of doing business.

Yeah, I can buy that.

> I could imagine a world where validations are completely independent of the model, and you add them to the Resource instead, but then you'd just be double-typing everything and would get out of sync.

Agreed that double-typing everything would be bad. 

Just thinking out loud, what do you think about specifying the validations to run `before_validation` in the Resource, rather than in the Model by using `on: :whatever` on the validations, and then using some kind of metaprogramming to dynamically add the `on: :whatever` clauses to the model validations while Grafiti is running? I realize this would be far more complex to implement and probably introduce hard to diagnose bugs (specifically with concurrency), of course :) 

In any case, I'm all for implementing `before_validation` hook solution now

**Comment by richmolj** [comment] 2019-03-30 16:06
@jnaglick my first impression is it's more trouble than its worth, but I'm up for some exploration once we have a `before_validation`  hook

**Comment by richmolj** [comment] 2019-03-30 16:07
@jnaglick I'm closing this specific issue and adding one for `before_validation`: https://github.com/graphiti-api/graphiti/issues/122

**Closed as completed by richmolj** 2019-03-30 16:07 UTC
